### ISSUE TITLE
[Beirut] Lightbox sizing is off by a smidge

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rice#100]
![2018-02-19_19-37-08](http://static.gitscout.com/cc029046c53cecaf701df4f03844df2ef0df553f9a757d279d4ced190cc23b2e.png)

**Comment by awoodruff** [comment]
I'm having trouble getting this. Which browser is that?

**Comment by davidheyman** [comment]
I'm not seeing it anymore either.
