### ISSUE TITLE
Change accent color throughout

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#117]
There was a request to use "Brazilian flag blue" (#032A74) instead of the current green.

The timeline background gradient should be: #92A1BE -> #032A74. I think everything else is self-explanatory, but let me know if you have any questions.

Do you need new banner images from me or can you make those? The XD file is updated with the new color.

![intro](https://user-images.githubusercontent.com/4501388/40189428-07868e2e-59c2-11e8-9dd7-4bd052554e76.png)

**Comment by davidheyman** [comment]
This should apply to the polygon highlight color as well.
