### ISSUE TITLE
Fix button formatting on landing page in Firefox

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#119]
![imaginerio](https://user-images.githubusercontent.com/4501388/40191366-ee1597fa-59c6-11e8-9463-bcc3f4987372.png)

**Comment by bcsheesley** [comment]
Looks good. Can "Begin Exploring" go on one line?

**Comment by bwellington** [comment]
Looks fine on my computer (must be os x / windows font rendering issue). I removed the fixed button width--let me know if this fixes the issue.

**Comment by bcsheesley** [comment]
Looks good to me!
