### ISSUE TITLE
Swap in new probe hint icon

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#123]
Can we see how this looks in place of the hand pointer?
`rice/src/font/click-to-explore.svg`

![rio-redesign](https://user-images.githubusercontent.com/4501388/40197613-97b371da-59d9-11e8-98fd-2a7f311b0510.png)

**Comment by bwellington** [comment]
Updated--see what you think. Also, to get custom svg to work with fontello you need to convert everything to a single compound path (convert fonts/icons to paths, etc).
