### ISSUE TITLE
Add a "no results found" message to the search results

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#136]
This would appear when clicking the map and nothing is found. And when searching via text input after 3 characters are entered.

**Comment by bcsheesley** [comment]
On second thought, I think this is probably needed when searching via text, but we can do without when searching via click or area and nothing is found.

**Comment by bwellington** [comment]
Added, but there are bugs--sometimes shows up on map click, sometimes doesn't. Need to investigate further.

**Comment by bcsheesley** [comment]
Seems to be working well for me. I'm closing it unless you know of specific cases to investigate.
