### ISSUE TITLE
Fix `explore by area` button mouseover

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#137]
I'm seeing this in Safari but not Firefox"

![button](https://user-images.githubusercontent.com/4501388/40204992-089bc760-59f0-11e8-9b26-ca5f519aadc4.gif)

**Comment by bwellington** [comment]
For the life of me I can't figure this one out. Seems to be an issue only in Safari 11--works fine in Edge, Chrome, Firefox, and Safari 10. It has something to do with the icons. The bug goes away if any text is included in the button.

**Comment by bwellington** [comment]
Ok, tried a hack fix for this. I still have no idea what was causing it. Works on Safari 11 on browserstack.
