### ISSUE TITLE
Make search by area tool tip semi-transparent

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#138]
![imaginerio-11](https://user-images.githubusercontent.com/4501388/40205080-5ea90d0c-59f0-11e8-8a8e-d1833c9bbfa5.png)

**Comment by bwellington** [comment]
I was struggling to recreate this. I think the issue is that you double clicked the button and the tool tip drew twice? Try clicking just once.

**Comment by bcsheesley** [comment]
I don't know what happened, but it's working now!
