### ISSUE TITLE
Gray text, icons, and buttons should get darker on mouse over

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#14]
E.g., this kind of thing can change to #333.

![instituterice](https://user-images.githubusercontent.com/4501388/32250815-010afcb2-be5c-11e7-8a16-e87f3e6dd044.png)

**Comment by awoodruff** [comment]
Hopefully deca487c2361dfc4e3cb16229554bb49982d4fb3 and 29674ee87d7ec11aa22c2be13875c95f64937c2c got everything
