### ISSUE TITLE
Use loading indicator on click probe

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rice#143]
It doesn't need to be the same one that is currently in imagineRio, but we need more than search results appearing in the sidebar to indicate that an action has occurred. 

@bcsheesley I'll let you decide if you want to keep that loading indicator or use a different one.

**Comment by bcsheesley** [comment]
I'd like to improve on what we currently do in imagineRio with an updated pulse animation.

Ideally, we'd play the pulse animation for a certain minimum amount of time on every click (even if results come in quickly) and continue to loop through until results come in.

Here's an svg, plus a gif fallback:
https://github.com/axismaps/rice/commit/3285f8840d2d04a94e3011102325e3739f25337d

**Comment by bwellington** [comment]
Added a click pulse animation (runs for the duration of the gif) and a spinning load screen that runs when layers are toggled, always for a minimum of 1/2 second.
