### ISSUE TITLE
Basemap background color missing

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#146]
I like how it looks like offshore clouds or fog, but we should probably fix it.

![screen shot 2018-05-18 at 10 53 55 am](https://user-images.githubusercontent.com/4501388/40244987-f1ae1f36-5a89-11e8-8e61-3a27c2483782.png)

**Comment by bwellington** [comment]
Do you know what the water rgb value is?

**Comment by bwellington** [comment]
Oh wait, this isn't an issue for me, never mind!
