### ISSUE TITLE
When plans are present, no other search results appear besides the plan

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#152]
Beaurepaire-Rohan, for example, prevents any other results from being returned via click or search-box.

**Comment by bwellington** [comment]
Is this still happening? I can't replicate the issue.

![plan_search](https://user-images.githubusercontent.com/11998214/40493653-271e62d2-5f41-11e8-80ff-c864f2685692.png)

**Comment by bcsheesley** [comment]
Not happening for me any more! Although, I now get other results (e.g., roads, buildings), I don't get maps and plans as results via click or box search. They only come in via text search, as shown in your example. Is that by design? I can't remember any reason why we wouldn't display them after any type of search.

**Comment by bwellington** [comment]
I believe this is a back-end issue--if any of those results came through from the API they would be displayed.

**Comment by davidheyman** [comment]
This is by design. The hit area for those things are so large it doesn't make sense to have them show up in a click search.
