### ISSUE TITLE
Style "New Member Registration" text like main/era title text

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#156]
Please make the font-weight `200`

![imaginerio](https://user-images.githubusercontent.com/4501388/40324633-b633e414-5cfe-11e8-9675-7057596283cd.png)

**Comment by bwellington** [comment]
It looks like the font weight is already equivalent to 200. Should I increase the font size to match the era titles? If I do, it won't fit on one line unless we increase the size of the register panel.

**Comment by bcsheesley** [comment]
The size is fine, but ideally the weight would match the other big titles, like this:

![screen shot 2018-05-25 at 9 48 40 am](https://user-images.githubusercontent.com/4501388/40550872-ed23f70c-6000-11e8-8551-17aeebd2f52b.png)

I had thought those were 200, but maybe 100 would do it?

**Comment by bwellington** [comment]
Strange, the titles all look exactly the same on my computer.

**Comment by bcsheesley** [comment]
This is looking correct to me now.
