### ISSUE TITLE
Style "Submit" button text like the "Begin Exploring" text

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#157]
![imaginerio](https://user-images.githubusercontent.com/4501388/40324708-ef762480-5cfe-11e8-949b-97bd31da1667.png)

![imaginerio](https://user-images.githubusercontent.com/4501388/40324719-fd641f52-5cfe-11e8-88d7-2f6483d2df86.png)

**Comment by bwellington** [comment]
I changed the font styles to match the "begin exploring" button, but these all look totally different than your screenshots on my computer, so I'm not sure if the issue is fixed or not.
