### ISSUE TITLE
Show legend swatches with search results

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#161]

**Comment by bcsheesley** [comment]
This looks great except for buildings, which sometimes do not have the swatch. Am I missing something? Or maybe not all building types are getting it?

![screen shot 2018-06-11 at 9 59 44 am](https://user-images.githubusercontent.com/4501388/41239725-71cea78a-6d5e-11e8-8907-9c457fe55879.png)

**Comment by bwellington** [comment]
There are a lot of buildings that are in sub-categories ("civil", for example) that we do not currently include in the legend or have swatch info for. Once we add that info to the legend the swatches will show up in the search results.
