### ISSUE TITLE
Urbanism->Areas swatch should be same size and shape as other line swatches

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#162]
Right now it looks taller and wider than the others. Maybe it can use the same svg as aqueducts, but with different dash-array values? I can also make a new svg to use for this.

![imaginerio-2](https://user-images.githubusercontent.com/4501388/40325971-4a06c090-5d03-11e8-8785-906a6392f77c.png)

**Comment by bwellington** [comment]
I'm not sure what's going on here, but when I make an SVG in Illustrator it renders totally differently in the map.

**Comment by davidheyman** [comment]
I think the tricky bit are these attributes from the opening `<svg>` tag:

```svg
width="60px" height="20px" viewBox="0 20 80 40" enable-background="new 0 20 80 40"
```

Check that and see if it helps, otherwise @bcsheesley can help make a new one. He's done loads of these.

**Comment by bwellington** [comment]
I think I got it--I had to manually copy over polyline attributes. I'm not sure why these weren't coming through directly from illustrator.
