### ISSUE TITLE
Swap in new 'explore by area' icon

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#164]
Can we give this a try? Instead of something that looks similar to regular search (which could be a bit confusing), this is meant to look more like the new "click-to-explore" icon. I'm not sure about size, but the hand pointers in both icons should be the same.

Hopefully, this SVG is helpful:
rice/src/font/explore-by-area.zip

![screen_shot_2018-05-21_at_3_26_04_pm](https://user-images.githubusercontent.com/4501388/40328276-725f8e3e-5d0b-11e8-8a7f-23c8b9dfddcb.png)

**Comment by bwellington** [comment]
I think I need the actual explore by area svg. Unless there's a way to transfer a custom icon from one fontello config to another.
