### ISSUE TITLE
Everything should fit on the splash screen

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#165]
Testing on my iPhone 7, there are issues with the language button obscuring the title (portrait mode) and "Jump to era" button obscuring the disclaimer (portrait and landscape modes).

For the language button, we could try swapping the text out for a globe icon when in portrait mode. For the buttons, it's possible that Jump to era and Begin exploring would fit side by side if 1) we remove the icons and 2) made the text a bit smaller.

![mobile](https://user-images.githubusercontent.com/4501388/40339837-cdd9df18-5d41-11e8-93d9-da878de7fe54.png)

**Comment by bcsheesley** [comment]
This is much better. Just a couple tweaks I see:

-Add a menu background (white is fine)
-Add some spacing between the language options for fat fingers
-Add a way to close the menu if nothing is selected (perhaps either by tapping the globe again or tapping away from the menu)

![img_7b9b77ca8ca2-1](https://user-images.githubusercontent.com/4501388/40736469-c07edcba-6403-11e8-8a11-2577b485a4d4.jpeg)

**Comment by bwellington** [comment]
Updated

**Comment by bcsheesley** [comment]
I'm still having trouble closing the menu in these two cases:

1. Tap globe icon (menu opens with English Version in bold).
2. Tap either away from menu, on the globe, or on the "English Version" text and the menu does not close.

1. Tap globe (menu opens with English Version in bold).
2. Tap Versão em Português (it turns black but the language doesn't change)
3. Tap Versão em Português again (the language changes but the menu doesn't go away)
4. Tap Versão em Português a third time and the menu closes.

**Comment by bcsheesley** [comment]
@bwellington let me know if/when this needs more testing.

**Comment by bwellington** [comment]
Updated--there were weird issues with mobile misinterpreting hover events. Does the Portuguese language option text look wrong to you when it isn't selected?

**Comment by bwellington** [comment]
Never mind, that should be fixed now as well

**Comment by bcsheesley** [comment]
Works great on desktop. On mobile, I have to tap the language name in the menu twice in order to get the menu to close. Ideally, it would close on selection, by tapping anywhere, or on the globe.

**Comment by bwellington** [comment]
Updated--there were some weird touch/click event issues going on. Let me know if it still isn't working correctly for you.

**Comment by bcsheesley** [comment]
It works!
