### ISSUE TITLE
Center the Shared Shelf button in the space below the image caption

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#176]
...and let the caption run full width.

![img_997ec70d92f3-1](https://user-images.githubusercontent.com/4501388/40341427-be77222a-5d4a-11e8-921d-3a85f65561a1.jpg)

**Comment by bcsheesley** [comment]
I was only able to test this on my iPhone7, but I still get the caption and button side-by-side in portrait mode.

![img_7d0a25e1b216-1](https://user-images.githubusercontent.com/4501388/40735878-043b953a-6402-11e8-819f-1d9fcefe0872.jpeg)

**Comment by bwellington** [comment]
Maybe I have the portrait breakpoint set too low. Do you know the pixel dimensions of your iphone screen?

**Comment by bcsheesley** [comment]
I believe it's 1334x750px

**Comment by bwellington** [comment]
I think the high dpi screens should be scaling to display correctly. Is your phone a 7+ or just 7?

**Comment by bwellington** [comment]
I made the portrait breakpoint bigger. Let me know if this fixes it.
