### ISSUE TITLE
Text size in portrait versus landscape

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#188]
Not sure if this is within our control, but I notice some text getting resized while other text does not when rotating my phone.

For example, in portrait mode image titles are bigger than image metadata, but in landscape this switches. Same thing with the "Return to Map" text, which is bigger in portrait but smaller than search results in landscape. Is it possible for the size hierarchy to stay consistent in either view?

Image text:
![img_4d82005ba7db-1](https://user-images.githubusercontent.com/4501388/41053455-2a8a580a-6981-11e8-931d-696fcb70b8a1.jpeg)

Search results text:
![img_e93d85e72516-1](https://user-images.githubusercontent.com/4501388/41053460-2da3b874-6981-11e8-9a82-879718f2250f.jpeg)

**Comment by bwellington** [comment]
Is this still happening? I can't recreate on my phone or browserstack. Seems like some kind of weird text scaling issue?
