### ISSUE TITLE
Clicking the text 'Return to legend' should also take you back to the legend

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rice#189]
![2018-06-07_15-50-23](http://static.gitscout.com/4561d46f6d635b023e7fe82dcf25326168c8ca37f4efd6dd6e3313316464f6c0.png)

**Comment by bwellington** [comment]
Updated. This is one @bcsheesley and I have gone back and forth on. I thought having the text act as a button might be confusing, as it looks the same as the text input.
