### ISSUE TITLE
Shift intro and era content upward

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#25]
I don't have an actual minimum height to target but noticed that the "Go to Map" button can get hidden behind the filmstrip on short-ish windows. There is a `line-height: 75px` on the `#intro h1` that if removed helps a little. Maybe things could get compressed some as well and still look decent.

![instituterice](https://user-images.githubusercontent.com/4501388/32291936-7c88706c-bf0c-11e7-9a9b-0f0c93c6d5d5.png)

**Comment by awoodruff** [comment]
Squeezed some things to get this reasonable down to 600px or so which hopefully is good enough. We'll see if adjustments are needed once there are real era descriptions.
