### ISSUE TITLE
Rivers missing from basemap

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#28]
Apparently, I only included styles for zoom=18 so need to fill these out for 15 and up.

**Comment by bcsheesley** [comment]
@davidheyman These are in the CSS now. Let me know what the best way is to get them into the XML.

**Comment by davidheyman** [comment]
This is ready for review as well

**Comment by bcsheesley** [comment]
The rivers look great, but I forgot the labels. Ugh. And while we're at it, we might as well add labels for water polygons, too.

1. Add river label styles. These can be found in the new layer called `#rivers_labels`.

1. Add water polygon label styles. These can be found in the new layer called `#water-poly-labels`.

This is the new XML:
https://www.dropbox.com/s/i25hhbnsb1td16z/rice.xml?dl=0

**Comment by bcsheesley** [comment]
Oh, one more thing. The new river labels require a new font. The CSS uses this variable:

`@bolditalic: "Helvetica Neue Bold Italic"; `
