### ISSUE TITLE
Basemap trees

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#3]
Some trees are missing shadows, and some shadows are missing trees.

**Comment by bcsheesley** [comment]
![instituterice](https://user-images.githubusercontent.com/4501388/32235607-f02e3086-be2d-11e7-80e5-941c6ea2cdb7.png)

**Comment by davidheyman** [comment]
I can’t get the shadow and point to render at the same place. Probably need to make 2 separate layers.

Is this how you have your CSS setup -> https://gis.stackexchange.com/questions/124842/rendering-two-shapes-for-point-and-overlapping-using-mapnik

**Comment by davidheyman** [comment]
Scratch that. Got it fixed.
