### ISSUE TITLE
Basemap design for zoom 15

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#4]
Currently missing most features

**Comment by bcsheesley** [comment]
Everything now starts at zoom 15. I know this will be a pain to add, so let me know if there's any way I can help.

This is the new XML, including zoom 15 and rivers (see #28):
https://www.dropbox.com/s/i25hhbnsb1td16z/rice.xml?dl=0

**Comment by davidheyman** [comment]
@bcsheesley Can you give this a review and close it out if everything looks good?
