### ISSUE TITLE
Add new label styles for Paths on the basemap

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#50]
Currently, Paths and Roads are getting the same styles but they really ought to be separated and given their own styles.

1. In `#roads_labels`, add a top level filter for “Roads”. The CSS now looks like `#roads_labels[FEATURETYP=“Roads”]`.

1. Add a new layer with label styles for “Paths”. The new styles can be found in `#roads_labels[FEATURECLA=“Paths”]`.

The new XML is here:
https://www.dropbox.com/s/i25hhbnsb1td16z/rice.xml?dl=0

**Comment by davidheyman** [comment]
@bcsheesley Does this new file have all the changes for this, #28, #7, and #4? I'd like to only do 1 more style update if possible.

**Comment by bcsheesley** [comment]
Yep, this includes all those changes. Thanks.
