### ISSUE TITLE
Persistant probing and search results

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#55]
On the desktop version, is there any reason this list shouldn't stick around after an item is selected? It's more difficult to explore nearby areas when it goes away and the mini-probe that replaces doesn't contain any new information. The list would then behave like legend features and have a selected state that could be toggled on/off.

**Comment by awoodruff** [comment]
I think that's a good idea. In the change I've just made, that mini-probe doesn't appear anymore; the item expands and is highlighted in the search/click results. Leaving this open until I'm confident I didn't mess up some other behavior in the process, though.

![screen shot 2017-12-07 at 12 07 32 pm](https://user-images.githubusercontent.com/3533462/33728061-3a9f376a-db47-11e7-89fb-ca0dd2699756.png)
