### ISSUE TITLE
Basemap street labels missing at zoom 18 and up

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#7]

**Comment by davidheyman** [comment]
Does there need to be a style or can I just change the scale threshold for the top rule?

**Comment by bcsheesley** [comment]
They need styles, but there should be styles for labels (and everything else) in the XML up to zoom 20.

**Comment by bcsheesley** [comment]
Sorry, I didn't answer very clearly before. The styles already exist in the XML. There shouldn't be a need to change the threshold or add anything new. I can see them in TileMill at z18 and above, just not online. Not sure what's going on...
