### ISSUE TITLE
[Beirut] Sort roads data

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#81]
Sort roads data so that it is drawn with bigger roads on top of smaller roads:

1. pedestrian
2. residential and tertiary (these get the same styles, so can be grouped, or not...)
3. secondary
4. primary
5. freeway

**Comment by davidheyman** [comment]
Is this right? Here's what I'm seeing:

![2018-02-19_12-25-09](http://static.gitscout.com/47e1b462e6d480b5f686ab0e300441fa2263e1d7c29a9e52b58f7926404968ef.png)

**Comment by bcsheesley** [comment]
I think we'll know for sure once `pedestrian` gets styled correctly. Right now it's getting classed with 'secondary' or 'primary' roads and is too high in the hierarchy. Pedestrian roads should end up at the bottom of the stacking order as in #80.

**Comment by bcsheesley** [comment]
Following up... it does look like all the residential roads are underneath primary and secondary roads, so that's a good sign.

**Comment by davidheyman** [comment]
The dataset that’s online now doesn’t have any pedestrian roads in it (unless they’re classified in the data incorrectly). Does that change things? The order it uses is:

Freeway
Primary
Secondary
Tertiary
Residential

**Comment by bcsheesley** [comment]
Okay, well, that order is good, and it appears to be working given the way the data is classified.

I'm surprised that what was once pedestrian is now primary or secondary, but like you said, maybe it's a misclassification. It certainly looked better the old way (without major roads going through a parking lot!).

![screen shot 2018-02-19 at 10 49 04 am](https://user-images.githubusercontent.com/4501388/36388801-aaa62bb8-1562-11e8-9d00-aafde9c1ace8.png)
